//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ConsoleTest.webticketinteragencias {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="webticketinteragenciasSoap", Namespace="http://webticketinteragencias.org/")]
    public partial class webticketinteragencias : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertaSolicitudOperationCompleted;
        
        private System.Threading.SendOrPostCallback HorarioEasyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CodigoPlanillaOperationCompleted;
        
        private System.Threading.SendOrPostCallback HorarioEasy_TESTOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertaSolicitud_TESTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public webticketinteragencias() {
            this.Url = global::ConsoleTest.Properties.Settings.Default.ConsoleTest_webticketinteragencias_webticketinteragencias;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertaSolicitudCompletedEventHandler InsertaSolicitudCompleted;
        
        /// <remarks/>
        public event HorarioEasyCompletedEventHandler HorarioEasyCompleted;
        
        /// <remarks/>
        public event CodigoPlanillaCompletedEventHandler CodigoPlanillaCompleted;
        
        /// <remarks/>
        public event HorarioEasy_TESTCompletedEventHandler HorarioEasy_TESTCompleted;
        
        /// <remarks/>
        public event InsertaSolicitud_TESTCompletedEventHandler InsertaSolicitud_TESTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webticketinteragencias.org/InsertaSolicitud", RequestNamespace="http://webticketinteragencias.org/", ResponseNamespace="http://webticketinteragencias.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertaSolicitud(Inserta_SolicitudEmisionRQ obj) {
            object[] results = this.Invoke("InsertaSolicitud", new object[] {
                        obj});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertaSolicitudAsync(Inserta_SolicitudEmisionRQ obj) {
            this.InsertaSolicitudAsync(obj, null);
        }
        
        /// <remarks/>
        public void InsertaSolicitudAsync(Inserta_SolicitudEmisionRQ obj, object userState) {
            if ((this.InsertaSolicitudOperationCompleted == null)) {
                this.InsertaSolicitudOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertaSolicitudOperationCompleted);
            }
            this.InvokeAsync("InsertaSolicitud", new object[] {
                        obj}, this.InsertaSolicitudOperationCompleted, userState);
        }
        
        private void OnInsertaSolicitudOperationCompleted(object arg) {
            if ((this.InsertaSolicitudCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertaSolicitudCompleted(this, new InsertaSolicitudCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webticketinteragencias.org/HorarioEasy", RequestNamespace="http://webticketinteragencias.org/", ResponseNamespace="http://webticketinteragencias.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HorarioRS HorarioEasy(HorarioRQ obj) {
            object[] results = this.Invoke("HorarioEasy", new object[] {
                        obj});
            return ((HorarioRS)(results[0]));
        }
        
        /// <remarks/>
        public void HorarioEasyAsync(HorarioRQ obj) {
            this.HorarioEasyAsync(obj, null);
        }
        
        /// <remarks/>
        public void HorarioEasyAsync(HorarioRQ obj, object userState) {
            if ((this.HorarioEasyOperationCompleted == null)) {
                this.HorarioEasyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHorarioEasyOperationCompleted);
            }
            this.InvokeAsync("HorarioEasy", new object[] {
                        obj}, this.HorarioEasyOperationCompleted, userState);
        }
        
        private void OnHorarioEasyOperationCompleted(object arg) {
            if ((this.HorarioEasyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HorarioEasyCompleted(this, new HorarioEasyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webticketinteragencias.org/CodigoPlanilla", RequestNamespace="http://webticketinteragencias.org/", ResponseNamespace="http://webticketinteragencias.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Planilla CodigoPlanilla(string strUsuWebLogin) {
            object[] results = this.Invoke("CodigoPlanilla", new object[] {
                        strUsuWebLogin});
            return ((Planilla)(results[0]));
        }
        
        /// <remarks/>
        public void CodigoPlanillaAsync(string strUsuWebLogin) {
            this.CodigoPlanillaAsync(strUsuWebLogin, null);
        }
        
        /// <remarks/>
        public void CodigoPlanillaAsync(string strUsuWebLogin, object userState) {
            if ((this.CodigoPlanillaOperationCompleted == null)) {
                this.CodigoPlanillaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCodigoPlanillaOperationCompleted);
            }
            this.InvokeAsync("CodigoPlanilla", new object[] {
                        strUsuWebLogin}, this.CodigoPlanillaOperationCompleted, userState);
        }
        
        private void OnCodigoPlanillaOperationCompleted(object arg) {
            if ((this.CodigoPlanillaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CodigoPlanillaCompleted(this, new CodigoPlanillaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webticketinteragencias.org/HorarioEasy_TEST", RequestNamespace="http://webticketinteragencias.org/", ResponseNamespace="http://webticketinteragencias.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HorarioRS HorarioEasy_TEST() {
            object[] results = this.Invoke("HorarioEasy_TEST", new object[0]);
            return ((HorarioRS)(results[0]));
        }
        
        /// <remarks/>
        public void HorarioEasy_TESTAsync() {
            this.HorarioEasy_TESTAsync(null);
        }
        
        /// <remarks/>
        public void HorarioEasy_TESTAsync(object userState) {
            if ((this.HorarioEasy_TESTOperationCompleted == null)) {
                this.HorarioEasy_TESTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHorarioEasy_TESTOperationCompleted);
            }
            this.InvokeAsync("HorarioEasy_TEST", new object[0], this.HorarioEasy_TESTOperationCompleted, userState);
        }
        
        private void OnHorarioEasy_TESTOperationCompleted(object arg) {
            if ((this.HorarioEasy_TESTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HorarioEasy_TESTCompleted(this, new HorarioEasy_TESTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webticketinteragencias.org/InsertaSolicitud_TEST", RequestNamespace="http://webticketinteragencias.org/", ResponseNamespace="http://webticketinteragencias.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertaSolicitud_TEST() {
            object[] results = this.Invoke("InsertaSolicitud_TEST", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertaSolicitud_TESTAsync() {
            this.InsertaSolicitud_TESTAsync(null);
        }
        
        /// <remarks/>
        public void InsertaSolicitud_TESTAsync(object userState) {
            if ((this.InsertaSolicitud_TESTOperationCompleted == null)) {
                this.InsertaSolicitud_TESTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertaSolicitud_TESTOperationCompleted);
            }
            this.InvokeAsync("InsertaSolicitud_TEST", new object[0], this.InsertaSolicitud_TESTOperationCompleted, userState);
        }
        
        private void OnInsertaSolicitud_TESTOperationCompleted(object arg) {
            if ((this.InsertaSolicitud_TESTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertaSolicitud_TESTCompleted(this, new InsertaSolicitud_TESTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webticketinteragencias.org/")]
    public partial class Inserta_SolicitudEmisionRQ {
        
        private string iPUsuarioField;
        
        private Signature signatureField;
        
        private int idWebField;
        
        private int idLangField;
        
        private int idUsuWebField;
        
        private string pnrCodField;
        
        private string tipoReservaField;
        
        private string promotorField;
        
        private double tarfBrutaField;
        
        private double igvField;
        
        private double porcentajeField;
        
        private double queuesField;
        
        private double otrosPagosField;
        
        private double incentivosField;
        
        private double tarfNetaField;
        
        private string observacionField;
        
        private int estadoField;
        
        private int idOfiDestinoField;
        
        private string tipoTarifaField;
        
        private int idUsuWebSegField;
        
        private string doc1Field;
        
        private string nroDoc1Field;
        
        private string doc2Field;
        
        private string nroDoc2Field;
        
        private int idUsuWebProcField;
        
        private int idDepDestinoField;
        
        private string nomPagadorField;
        
        private string apePagadorField;
        
        private SolicitudItinerario[] itinerariosField;
        
        private SolicitudPago[] pagosField;
        
        private SolicitudPasajero[] pasajerosField;
        
        private string paisDestinoField;
        
        private string sabreAmadeusField;
        
        private short sistemaOrigenField;
        
        private string nomBancoField;
        
        private string nomBanco2Field;
        
        private string codSeguridadTarjField;
        
        private System.Nullable<int> idPuntoEmisionField;
        
        private System.Nullable<int> idsucursalEmisionField;
        
        private System.Nullable<int> conWaiverField;
        
        private System.Nullable<int> idSubCodigoField;
        
        private string fileReferenciaField;
        
        private string nomSucBancoField;
        
        private string referenciaField;
        
        private string nomImagenField;
        
        private string enviaDepositoField;
        
        private string strNombrePaginaField;
        
        /// <remarks/>
        public string iPUsuario {
            get {
                return this.iPUsuarioField;
            }
            set {
                this.iPUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public Signature signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
        
        /// <remarks/>
        public int idWeb {
            get {
                return this.idWebField;
            }
            set {
                this.idWebField = value;
            }
        }
        
        /// <remarks/>
        public int idLang {
            get {
                return this.idLangField;
            }
            set {
                this.idLangField = value;
            }
        }
        
        /// <remarks/>
        public int idUsuWeb {
            get {
                return this.idUsuWebField;
            }
            set {
                this.idUsuWebField = value;
            }
        }
        
        /// <remarks/>
        public string pnrCod {
            get {
                return this.pnrCodField;
            }
            set {
                this.pnrCodField = value;
            }
        }
        
        /// <remarks/>
        public string tipoReserva {
            get {
                return this.tipoReservaField;
            }
            set {
                this.tipoReservaField = value;
            }
        }
        
        /// <remarks/>
        public string promotor {
            get {
                return this.promotorField;
            }
            set {
                this.promotorField = value;
            }
        }
        
        /// <remarks/>
        public double tarfBruta {
            get {
                return this.tarfBrutaField;
            }
            set {
                this.tarfBrutaField = value;
            }
        }
        
        /// <remarks/>
        public double igv {
            get {
                return this.igvField;
            }
            set {
                this.igvField = value;
            }
        }
        
        /// <remarks/>
        public double porcentaje {
            get {
                return this.porcentajeField;
            }
            set {
                this.porcentajeField = value;
            }
        }
        
        /// <remarks/>
        public double queues {
            get {
                return this.queuesField;
            }
            set {
                this.queuesField = value;
            }
        }
        
        /// <remarks/>
        public double otrosPagos {
            get {
                return this.otrosPagosField;
            }
            set {
                this.otrosPagosField = value;
            }
        }
        
        /// <remarks/>
        public double incentivos {
            get {
                return this.incentivosField;
            }
            set {
                this.incentivosField = value;
            }
        }
        
        /// <remarks/>
        public double tarfNeta {
            get {
                return this.tarfNetaField;
            }
            set {
                this.tarfNetaField = value;
            }
        }
        
        /// <remarks/>
        public string observacion {
            get {
                return this.observacionField;
            }
            set {
                this.observacionField = value;
            }
        }
        
        /// <remarks/>
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public int idOfiDestino {
            get {
                return this.idOfiDestinoField;
            }
            set {
                this.idOfiDestinoField = value;
            }
        }
        
        /// <remarks/>
        public string tipoTarifa {
            get {
                return this.tipoTarifaField;
            }
            set {
                this.tipoTarifaField = value;
            }
        }
        
        /// <remarks/>
        public int idUsuWebSeg {
            get {
                return this.idUsuWebSegField;
            }
            set {
                this.idUsuWebSegField = value;
            }
        }
        
        /// <remarks/>
        public string doc1 {
            get {
                return this.doc1Field;
            }
            set {
                this.doc1Field = value;
            }
        }
        
        /// <remarks/>
        public string nroDoc1 {
            get {
                return this.nroDoc1Field;
            }
            set {
                this.nroDoc1Field = value;
            }
        }
        
        /// <remarks/>
        public string doc2 {
            get {
                return this.doc2Field;
            }
            set {
                this.doc2Field = value;
            }
        }
        
        /// <remarks/>
        public string nroDoc2 {
            get {
                return this.nroDoc2Field;
            }
            set {
                this.nroDoc2Field = value;
            }
        }
        
        /// <remarks/>
        public int idUsuWebProc {
            get {
                return this.idUsuWebProcField;
            }
            set {
                this.idUsuWebProcField = value;
            }
        }
        
        /// <remarks/>
        public int idDepDestino {
            get {
                return this.idDepDestinoField;
            }
            set {
                this.idDepDestinoField = value;
            }
        }
        
        /// <remarks/>
        public string nomPagador {
            get {
                return this.nomPagadorField;
            }
            set {
                this.nomPagadorField = value;
            }
        }
        
        /// <remarks/>
        public string apePagador {
            get {
                return this.apePagadorField;
            }
            set {
                this.apePagadorField = value;
            }
        }
        
        /// <remarks/>
        public SolicitudItinerario[] itinerarios {
            get {
                return this.itinerariosField;
            }
            set {
                this.itinerariosField = value;
            }
        }
        
        /// <remarks/>
        public SolicitudPago[] pagos {
            get {
                return this.pagosField;
            }
            set {
                this.pagosField = value;
            }
        }
        
        /// <remarks/>
        public SolicitudPasajero[] pasajeros {
            get {
                return this.pasajerosField;
            }
            set {
                this.pasajerosField = value;
            }
        }
        
        /// <remarks/>
        public string paisDestino {
            get {
                return this.paisDestinoField;
            }
            set {
                this.paisDestinoField = value;
            }
        }
        
        /// <remarks/>
        public string sabreAmadeus {
            get {
                return this.sabreAmadeusField;
            }
            set {
                this.sabreAmadeusField = value;
            }
        }
        
        /// <remarks/>
        public short sistemaOrigen {
            get {
                return this.sistemaOrigenField;
            }
            set {
                this.sistemaOrigenField = value;
            }
        }
        
        /// <remarks/>
        public string nomBanco {
            get {
                return this.nomBancoField;
            }
            set {
                this.nomBancoField = value;
            }
        }
        
        /// <remarks/>
        public string nomBanco2 {
            get {
                return this.nomBanco2Field;
            }
            set {
                this.nomBanco2Field = value;
            }
        }
        
        /// <remarks/>
        public string codSeguridadTarj {
            get {
                return this.codSeguridadTarjField;
            }
            set {
                this.codSeguridadTarjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> idPuntoEmision {
            get {
                return this.idPuntoEmisionField;
            }
            set {
                this.idPuntoEmisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> idsucursalEmision {
            get {
                return this.idsucursalEmisionField;
            }
            set {
                this.idsucursalEmisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> conWaiver {
            get {
                return this.conWaiverField;
            }
            set {
                this.conWaiverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> idSubCodigo {
            get {
                return this.idSubCodigoField;
            }
            set {
                this.idSubCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string fileReferencia {
            get {
                return this.fileReferenciaField;
            }
            set {
                this.fileReferenciaField = value;
            }
        }
        
        /// <remarks/>
        public string nomSucBanco {
            get {
                return this.nomSucBancoField;
            }
            set {
                this.nomSucBancoField = value;
            }
        }
        
        /// <remarks/>
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
        
        /// <remarks/>
        public string nomImagen {
            get {
                return this.nomImagenField;
            }
            set {
                this.nomImagenField = value;
            }
        }
        
        /// <remarks/>
        public string enviaDeposito {
            get {
                return this.enviaDepositoField;
            }
            set {
                this.enviaDepositoField = value;
            }
        }
        
        /// <remarks/>
        public string strNombrePagina {
            get {
                return this.strNombrePaginaField;
            }
            set {
                this.strNombrePaginaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webticketinteragencias.org/")]
    public partial class Signature {
        
        private short idWebField;
        
        private short idLangField;
        
        private string ipField;
        
        private string keyAccessField;
        
        private string usuarioField;
        
        private short idSecuenciaField;
        
        private string browserField;
        
        private string rUCField;
        
        private string razonSocialField;
        
        private short idDispositivoField;
        
        /// <remarks/>
        public short idWeb {
            get {
                return this.idWebField;
            }
            set {
                this.idWebField = value;
            }
        }
        
        /// <remarks/>
        public short idLang {
            get {
                return this.idLangField;
            }
            set {
                this.idLangField = value;
            }
        }
        
        /// <remarks/>
        public string ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        public string keyAccess {
            get {
                return this.keyAccessField;
            }
            set {
                this.keyAccessField = value;
            }
        }
        
        /// <remarks/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public short idSecuencia {
            get {
                return this.idSecuenciaField;
            }
            set {
                this.idSecuenciaField = value;
            }
        }
        
        /// <remarks/>
        public string browser {
            get {
                return this.browserField;
            }
            set {
                this.browserField = value;
            }
        }
        
        /// <remarks/>
        public string rUC {
            get {
                return this.rUCField;
            }
            set {
                this.rUCField = value;
            }
        }
        
        /// <remarks/>
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
            }
        }
        
        /// <remarks/>
        public short idDispositivo {
            get {
                return this.idDispositivoField;
            }
            set {
                this.idDispositivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webticketinteragencias.org/")]
    public partial class Planilla {
        
        private string strIdEmpresaPlanillaField;
        
        private string strIdCodigoPlanillaField;
        
        /// <remarks/>
        public string strIdEmpresaPlanilla {
            get {
                return this.strIdEmpresaPlanillaField;
            }
            set {
                this.strIdEmpresaPlanillaField = value;
            }
        }
        
        /// <remarks/>
        public string strIdCodigoPlanilla {
            get {
                return this.strIdCodigoPlanillaField;
            }
            set {
                this.strIdCodigoPlanillaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webticketinteragencias.org/")]
    public partial class HorarioRS {
        
        private int intPermitirAutomaticaField;
        
        private int intPermitirCounterField;
        
        /// <remarks/>
        public int intPermitirAutomatica {
            get {
                return this.intPermitirAutomaticaField;
            }
            set {
                this.intPermitirAutomaticaField = value;
            }
        }
        
        /// <remarks/>
        public int intPermitirCounter {
            get {
                return this.intPermitirCounterField;
            }
            set {
                this.intPermitirCounterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webticketinteragencias.org/")]
    public partial class HorarioRQ {
        
        private CondicionAgy eCondicionAgyField;
        
        private int intIdWebField;
        
        private ModuloEasy eModuloEasyField;
        
        private int intOpcionField;
        
        /// <remarks/>
        public CondicionAgy eCondicionAgy {
            get {
                return this.eCondicionAgyField;
            }
            set {
                this.eCondicionAgyField = value;
            }
        }
        
        /// <remarks/>
        public int intIdWeb {
            get {
                return this.intIdWebField;
            }
            set {
                this.intIdWebField = value;
            }
        }
        
        /// <remarks/>
        public ModuloEasy eModuloEasy {
            get {
                return this.eModuloEasyField;
            }
            set {
                this.eModuloEasyField = value;
            }
        }
        
        /// <remarks/>
        public int intOpcion {
            get {
                return this.intOpcionField;
            }
            set {
                this.intOpcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webticketinteragencias.org/")]
    public enum CondicionAgy {
        
        /// <remarks/>
        CON,
        
        /// <remarks/>
        CRED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webticketinteragencias.org/")]
    public enum ModuloEasy {
        
        /// <remarks/>
        Emision,
        
        /// <remarks/>
        Void,
        
        /// <remarks/>
        Changer,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webticketinteragencias.org/")]
    public partial class SolicitudPasajero {
        
        private string tipoPasajeroField;
        
        private string nombrePasajeroField;
        
        private string nroDocumentoField;
        
        private string tipoDocumentoField;
        
        private string tipoDocumentoSabreField;
        
        private string documentoSabreField;
        
        private string fechaNacimientoField;
        
        private string sexoField;
        
        private string strNumeroPaxField;
        
        private string strNumeroRUCField;
        
        /// <remarks/>
        public string tipoPasajero {
            get {
                return this.tipoPasajeroField;
            }
            set {
                this.tipoPasajeroField = value;
            }
        }
        
        /// <remarks/>
        public string nombrePasajero {
            get {
                return this.nombrePasajeroField;
            }
            set {
                this.nombrePasajeroField = value;
            }
        }
        
        /// <remarks/>
        public string nroDocumento {
            get {
                return this.nroDocumentoField;
            }
            set {
                this.nroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string tipoDocumentoSabre {
            get {
                return this.tipoDocumentoSabreField;
            }
            set {
                this.tipoDocumentoSabreField = value;
            }
        }
        
        /// <remarks/>
        public string documentoSabre {
            get {
                return this.documentoSabreField;
            }
            set {
                this.documentoSabreField = value;
            }
        }
        
        /// <remarks/>
        public string fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        public string strNumeroPax {
            get {
                return this.strNumeroPaxField;
            }
            set {
                this.strNumeroPaxField = value;
            }
        }
        
        /// <remarks/>
        public string strNumeroRUC {
            get {
                return this.strNumeroRUCField;
            }
            set {
                this.strNumeroRUCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webticketinteragencias.org/")]
    public partial class SolicitudPago {
        
        private int idPagoField;
        
        private string pagoTipoField;
        
        private string pagoCashField;
        
        private string pagoTarjetaField;
        
        private string pagoTipoTarjetaField;
        
        private string nroTarjetaField;
        
        private System.Nullable<System.DateTime> fechVenTarjetaField;
        
        private string titularTarjetaField;
        
        private int idPaisTarjetaField;
        
        private string bancoTitularTarjetaField;
        
        private string idDocumentoField;
        
        private string nroDocumentoField;
        
        private int idiOfiField;
        
        private string nroCuentaField;
        
        private string nroOperacionField;
        
        private string montoField;
        
        private System.Nullable<System.DateTime> fechDepositoField;
        
        private int idiOfi2Field;
        
        private string nroCuenta2Field;
        
        private string nroOperacion2Field;
        
        private string monto2Field;
        
        private System.Nullable<System.DateTime> fechDeposito2Field;
        
        private string strNombreBancoField;
        
        private string strNombreBanco2Field;
        
        private string strCodSeguridadField;
        
        private string strSucursalBancoField;
        
        private string strReferenciaDepositoField;
        
        private string strNombreArchivoField;
        
        /// <remarks/>
        public int idPago {
            get {
                return this.idPagoField;
            }
            set {
                this.idPagoField = value;
            }
        }
        
        /// <remarks/>
        public string pagoTipo {
            get {
                return this.pagoTipoField;
            }
            set {
                this.pagoTipoField = value;
            }
        }
        
        /// <remarks/>
        public string pagoCash {
            get {
                return this.pagoCashField;
            }
            set {
                this.pagoCashField = value;
            }
        }
        
        /// <remarks/>
        public string pagoTarjeta {
            get {
                return this.pagoTarjetaField;
            }
            set {
                this.pagoTarjetaField = value;
            }
        }
        
        /// <remarks/>
        public string pagoTipoTarjeta {
            get {
                return this.pagoTipoTarjetaField;
            }
            set {
                this.pagoTipoTarjetaField = value;
            }
        }
        
        /// <remarks/>
        public string nroTarjeta {
            get {
                return this.nroTarjetaField;
            }
            set {
                this.nroTarjetaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fechVenTarjeta {
            get {
                return this.fechVenTarjetaField;
            }
            set {
                this.fechVenTarjetaField = value;
            }
        }
        
        /// <remarks/>
        public string titularTarjeta {
            get {
                return this.titularTarjetaField;
            }
            set {
                this.titularTarjetaField = value;
            }
        }
        
        /// <remarks/>
        public int idPaisTarjeta {
            get {
                return this.idPaisTarjetaField;
            }
            set {
                this.idPaisTarjetaField = value;
            }
        }
        
        /// <remarks/>
        public string bancoTitularTarjeta {
            get {
                return this.bancoTitularTarjetaField;
            }
            set {
                this.bancoTitularTarjetaField = value;
            }
        }
        
        /// <remarks/>
        public string idDocumento {
            get {
                return this.idDocumentoField;
            }
            set {
                this.idDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string nroDocumento {
            get {
                return this.nroDocumentoField;
            }
            set {
                this.nroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public int idiOfi {
            get {
                return this.idiOfiField;
            }
            set {
                this.idiOfiField = value;
            }
        }
        
        /// <remarks/>
        public string nroCuenta {
            get {
                return this.nroCuentaField;
            }
            set {
                this.nroCuentaField = value;
            }
        }
        
        /// <remarks/>
        public string nroOperacion {
            get {
                return this.nroOperacionField;
            }
            set {
                this.nroOperacionField = value;
            }
        }
        
        /// <remarks/>
        public string monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fechDeposito {
            get {
                return this.fechDepositoField;
            }
            set {
                this.fechDepositoField = value;
            }
        }
        
        /// <remarks/>
        public int idiOfi2 {
            get {
                return this.idiOfi2Field;
            }
            set {
                this.idiOfi2Field = value;
            }
        }
        
        /// <remarks/>
        public string nroCuenta2 {
            get {
                return this.nroCuenta2Field;
            }
            set {
                this.nroCuenta2Field = value;
            }
        }
        
        /// <remarks/>
        public string nroOperacion2 {
            get {
                return this.nroOperacion2Field;
            }
            set {
                this.nroOperacion2Field = value;
            }
        }
        
        /// <remarks/>
        public string monto2 {
            get {
                return this.monto2Field;
            }
            set {
                this.monto2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fechDeposito2 {
            get {
                return this.fechDeposito2Field;
            }
            set {
                this.fechDeposito2Field = value;
            }
        }
        
        /// <remarks/>
        public string strNombreBanco {
            get {
                return this.strNombreBancoField;
            }
            set {
                this.strNombreBancoField = value;
            }
        }
        
        /// <remarks/>
        public string strNombreBanco2 {
            get {
                return this.strNombreBanco2Field;
            }
            set {
                this.strNombreBanco2Field = value;
            }
        }
        
        /// <remarks/>
        public string strCodSeguridad {
            get {
                return this.strCodSeguridadField;
            }
            set {
                this.strCodSeguridadField = value;
            }
        }
        
        /// <remarks/>
        public string strSucursalBanco {
            get {
                return this.strSucursalBancoField;
            }
            set {
                this.strSucursalBancoField = value;
            }
        }
        
        /// <remarks/>
        public string strReferenciaDeposito {
            get {
                return this.strReferenciaDepositoField;
            }
            set {
                this.strReferenciaDepositoField = value;
            }
        }
        
        /// <remarks/>
        public string strNombreArchivo {
            get {
                return this.strNombreArchivoField;
            }
            set {
                this.strNombreArchivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webticketinteragencias.org/")]
    public partial class SolicitudItinerario {
        
        private string lineaAereaField;
        
        private string nroVueloField;
        
        private string claseField;
        
        private System.DateTime fechaVueloField;
        
        private string origenVueloField;
        
        private string destinoVueloField;
        
        private string familyFareField;
        
        /// <remarks/>
        public string lineaAerea {
            get {
                return this.lineaAereaField;
            }
            set {
                this.lineaAereaField = value;
            }
        }
        
        /// <remarks/>
        public string nroVuelo {
            get {
                return this.nroVueloField;
            }
            set {
                this.nroVueloField = value;
            }
        }
        
        /// <remarks/>
        public string clase {
            get {
                return this.claseField;
            }
            set {
                this.claseField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaVuelo {
            get {
                return this.fechaVueloField;
            }
            set {
                this.fechaVueloField = value;
            }
        }
        
        /// <remarks/>
        public string origenVuelo {
            get {
                return this.origenVueloField;
            }
            set {
                this.origenVueloField = value;
            }
        }
        
        /// <remarks/>
        public string destinoVuelo {
            get {
                return this.destinoVueloField;
            }
            set {
                this.destinoVueloField = value;
            }
        }
        
        /// <remarks/>
        public string familyFare {
            get {
                return this.familyFareField;
            }
            set {
                this.familyFareField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void InsertaSolicitudCompletedEventHandler(object sender, InsertaSolicitudCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertaSolicitudCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertaSolicitudCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void HorarioEasyCompletedEventHandler(object sender, HorarioEasyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HorarioEasyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HorarioEasyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HorarioRS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HorarioRS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CodigoPlanillaCompletedEventHandler(object sender, CodigoPlanillaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CodigoPlanillaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CodigoPlanillaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Planilla Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Planilla)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void HorarioEasy_TESTCompletedEventHandler(object sender, HorarioEasy_TESTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HorarioEasy_TESTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HorarioEasy_TESTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HorarioRS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HorarioRS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void InsertaSolicitud_TESTCompletedEventHandler(object sender, InsertaSolicitud_TESTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertaSolicitud_TESTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertaSolicitud_TESTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591